language: java

# Oracle JDK 7 reached End of Life in April 2015.
# Oracle JDK 10 reached End of Life in October 2018.

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: linux
      dist: xenial
      jdk: openjdk10
    - os: linux
      dist: xenial
      jdk: oraclejdk11
    - os: linux
      dist: xenial
      jdk: openjdk11
    - os: linux
      dist: xenial
      jdk: openjdk12
    - os: linux
      dist: xenial
      jdk: oraclejdk13
    - os: linux
      dist: xenial
      jdk: openjdk13

after_success:
  - mvn clean cobertura:cobertura coveralls:report

cache:
  directories:
    - $HOME/.m2
